// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0hSijmgHIkJ9SeXjg7LcZBgqT51iN7l4',
    appId: '1:1071877936765:web:e11990dc070dbd64e10314',
    messagingSenderId: '1071877936765',
    projectId: 'brofit1-2d221',
    authDomain: 'brofit1-2d221.firebaseapp.com',
    storageBucket: 'brofit1-2d221.appspot.com',
    measurementId: 'G-SLX3G321Q2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXf6k-WZg6Fe6rOiscmR9IPsOvWbj9tUs',
    appId: '1:1071877936765:android:49266a8b2f0c4164e10314',
    messagingSenderId: '1071877936765',
    projectId: 'brofit1-2d221',
    storageBucket: 'brofit1-2d221.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJvGLxArl84Yua3_b3bjzL4FK_jvXX_Ok',
    appId: '1:1071877936765:ios:6083b57757ed9da4e10314',
    messagingSenderId: '1071877936765',
    projectId: 'brofit1-2d221',
    storageBucket: 'brofit1-2d221.appspot.com',
    iosBundleId: 'com.example.fitnessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJvGLxArl84Yua3_b3bjzL4FK_jvXX_Ok',
    appId: '1:1071877936765:ios:45be455bfbcf44c7e10314',
    messagingSenderId: '1071877936765',
    projectId: 'brofit1-2d221',
    storageBucket: 'brofit1-2d221.appspot.com',
    iosBundleId: 'com.example.fitnessApp.RunnerTests',
  );
}
